spring:
  application:
    name: ContentService
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/contentdb
    username: postgres
    password: sam2424
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/StudyBuddyRealm

server:
  port: 8082

minio:
  url: http://localhost:9000
  access:
    name: 5LOINNTM4WLINUNUXOR1
    secret: CTfTZCCMHSezoWL4gh09Uaj65Z2UC2MjLDW8bPI7
  bucket:
    name: contentpdfai

rabbitmq:
  exchange:
    name: content.exchange
  queue:
    name: content.queue
  routing:
    key: content.routing.key
